### ISSUE TITLE
May I ask about a line of lhs_generators?

### ISSUE THREAD

**Issue by luzai** [simonbowly/lp-generators#2]
Hi simonbowly, 

May I ask why [here](https://github.com/simonbowly/lp-generators/blob/937c44074c234333b6a5408c3e18f498c2205948/lp_generators/lhs_generators.py#L88) is `degree2[v2] += 2` instead of `degree2[v2] += 1`? 

Thank you!

Best,
Luzai

**Comment by simonbowly** [comment]
I am not sure sorry, it looks like a mistake to me, it should be 1 to correctly track the degree.

**Comment by luzai** [comment]
Hi simonbowly, 

Thank you for your reply! I agree with you and I think it may not have big impact when the density is lower than 0.3. But I would still recommend updating this line for correctness. 

Best,
Luzai
